services:
  postgres:
    image: postgres:16-alpine
    container_name: contro_gastos_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: contro_gastos
      POSTGRES_PASSWORD: contro_gastos
      POSTGRES_DB: contro_gastos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
